[package]
name = "open-pi-scope"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
tokio = { version = "1.44.1", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec"] }
gpsd_proto = "1.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0.97"
critical-section = {version="1.2.0",features = ["std"]}
derivative = "2.2.0"
tonic = "0.12.3"
tonic-reflection = "0.12.3"
prost = "0.13"
world_magnetic_model = "0.2.0"
chrono = "0.4.40"


[build-dependencies]
protoc-bin-vendored = "3"
tonic-build = "0.12.3"
